<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>GetQuote</name>
   <tag></tag>
   <elementGuidId>55e92a8a-804a-4321-a066-01618299ba0d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <restRequestMethod></restRequestMethod>
   <restUrl></restUrl>
   <serviceType>SOAP</serviceType>
   <soapBody>&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?>&lt;SOAP-ENV:Envelope xmlns:SOAP-ENV=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:tns=&quot;http://ws.cdyne.com/&quot;>
  &lt;SOAP-ENV:Header/>
  &lt;SOAP-ENV:Body>
    &lt;tns:GetQuote>
      &lt;tns:StockSymbol>?&lt;/tns:StockSymbol>
      &lt;tns:LicenseKey>?&lt;/tns:LicenseKey>
    &lt;/tns:GetQuote>
  &lt;/SOAP-ENV:Body>
&lt;/SOAP-ENV:Envelope>
</soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod>SOAP12</soapRequestMethod>
   <soapServiceFunction>GetQuote</soapServiceFunction>
   <wsdlAddress>http://ws.cdyne.com/delayedstockquote/delayedstockquote.asmx?wsdl</wsdlAddress>
</WebServiceRequestEntity>
