<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>GetQuoteDataSet</name>
   <tag></tag>
   <elementGuidId>9a5782db-74e5-420e-92d3-7ccdb8502441</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <restRequestMethod></restRequestMethod>
   <restUrl></restUrl>
   <serviceType>SOAP</serviceType>
   <soapBody>&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?>&lt;SOAP-ENV:Envelope xmlns:SOAP-ENV=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:tns=&quot;http://ws.cdyne.com/&quot;>
  &lt;SOAP-ENV:Header/>
  &lt;SOAP-ENV:Body>
    &lt;tns:GetQuoteDataSet>
      &lt;tns:StockSymbols>?&lt;/tns:StockSymbols>
      &lt;tns:LicenseKey>?&lt;/tns:LicenseKey>
    &lt;/tns:GetQuoteDataSet>
  &lt;/SOAP-ENV:Body>
&lt;/SOAP-ENV:Envelope>
</soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod>SOAP</soapRequestMethod>
   <soapServiceFunction>GetQuoteDataSet</soapServiceFunction>
   <wsdlAddress>http://ws.cdyne.com/delayedstockquote/delayedstockquote.asmx?wsdl</wsdlAddress>
</WebServiceRequestEntity>
